### ISSUE TITLE
数据怎么使用

### ISSUE THREAD

**Issue by beiyixiang** [chuanting/FedDA#1]
下载下来的数据怎么在代码中使用啊

**Comment by chuanting** [comment]
@beiyixiang 数据下载下来的话，直接放到本地，然后改变https://github.com/chuanting/FedDA/blob/4a95702719ba2efc3d6eb542431ca8952854860c/utils/misc.py#L166 这一行代码，换成你的路径即可运行程序。

**Comment by beiyixiang** [comment]
是我的数据的问题吗？是不是需要把下载下来的txt数据变成.h5类型的啊

**Comment by chuanting** [comment]
> 是我的数据的问题吗？是不是需要把下载下来的txt数据变成.h5类型的啊

你好，我不清楚你下载的数据是什么。如果你需要我论文里面的数据，我可以邮件发给你。

**Comment by beiyixiang** [comment]
18851768884@163.com
谢谢

**Comment by chuanting** [comment]
> [18851768884@163.com](mailto:18851768884@163.com)
> 谢谢

邮件已发。我将关闭该Issue。
