### ISSUE TITLE
error

### ISSUE THREAD

**Issue by clianchen** [chuanting/FedDA#3]
OSError: Unable to open file (unable to open file: name = 'D:\Paper\HBUT\First semester\RL\Code\FedDA-main/dataset/trento.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I ran the code, but the above error occurred. How should I solve this? Looking forward to your answer, my email is 2596943802@qq.com

**Comment by chuanting** [comment]
@clianchen Hi there. Looks like the file path is not correct. Please download the [datasets](https://github.com/chuanting/FedDA#datasets) and put them into an appropriate folder. Then the code should run correctly.

**Comment by chuanting** [comment]
@clianchen Hi clianchen, I now close this issue. If you still have any questions, please send me an email.
