### ISSUE TITLE
module missing

### ISSUE THREAD

**Issue by vink1994** [chuanting/FedDA#4]
module missing
Traceback (most recent call last):
  File "D:\\FedDA-main\FedDA-main\fed_att_algo.py", line 23, in <module>
    from DualFedAtt.utils.misc import args_parser, average_weights_att
ModuleNotFoundError: No module named 'DualFedAtt'
Press any key to continue . . .

**Comment by chuanting** [comment]
@vink1994 remove the folder 'DualFedAtt' like [here](https://codeocean.com/capsule/4767521/tree).

**Comment by vink1994** [comment]
no permission to access codeocean, kindly guide 
it is showing :You don't have permission to access this compute capsule

**Comment by chuanting** [comment]
@vink1994 sorry for sending you the wrong link. The publicly avaliable link is [this one](https://codeocean.com/capsule/4884085/tree/v1)

**Comment by vink1994** [comment]
hi thanks for the reply, 
I am not able to figure out which folder to remove as both  code looks similar
